dm_user:
    resource: "@DMUserBundle/Resources/config/routing.yml"
    prefix:   /

dm_resource:
    resource: "@DMResourceBundle/Resources/config/routing.yml"
    prefix:   /

dm_document:
    resource: "@DMDocumentBundle/Controller/"
    type:  annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
